front/models.py
from flask_login import UserMixin
from .start import db

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))
    creation_date = db.Column(db.String(1000))

front/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import current_user, login_user, login_required, logout_user
from datetime import datetime
from .models import User
from .start import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect("/dashboard", code=302)
    else:
        return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    # login code goes here
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.dashboard'))

@auth.route('/signup')
def signup():
    if current_user.is_authenticated:
        return redirect("/dashboard", code=302)
    else:
        return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    # code to validate and add user to database goes here
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    now = datetime.now()
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'), creation_date=now.strftime("%d/%m/%Y %H:%M:%S"))

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

front/routes.py
import json
import os
import sqlite3 as sql
from flask import Blueprint, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required
from front.db_action import get_db_connection
from instances.main import drop
from .models import User
from .start import db

main = Blueprint('main', __name__)

@main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect("/dashboard", code=302)
    else:
        return render_template('login.html')

@main.route('/dashboard')
@login_required
def dashboard():
    conn = get_db_connection()
    workers = conn.execute('SELECT instance_name, internal_ip, task_progression, task_wordlist, instance_status, status FROM instances INNER JOIN tasks ON instances.task_id = tasks.id WHERE user_id = ?', (current_user.get_id()))
                
    return render_template('dashboard.html', workers=workers)

@main.route('/attack')
@login_required
def attack():
    conn = get_db_connection()
    hash_type = conn.execute('SELECT type_name FROM hash_type')
    wordlists = conn.execute('SELECT name FROM wordlists')
    return render_template('attack.html', hash_type=hash_type, wordlists=wordlists)

@main.route('/wordlist')
@login_required
def wordlist():
    conn = get_db_connection()
    wordlists = conn.execute('SELECT id, name, url FROM wordlists')
    return render_template('wordlist.html', wordlists=wordlists)

@main.route('/wordlist', methods=['POST'])
@login_required
def add_wordlist():
    conn = get_db_connection()
    sql = ''' INSERT INTO wordlists(name,url)
              VALUES(?,?) '''
    cursor = conn.cursor()
    cursor.execute(sql, (request.form.get('name'),request.form.get('url')))
    conn.commit()
    return redirect(url_for('main.wordlist'))

@main.route('/wordlist/delete/<id>', methods=['POST'])
@login_required
def del_wordlist(id):
    conn = get_db_connection()

    # Remove a row
    sql = 'DELETE FROM wordlists WHERE id=?'
    cur = conn.cursor()
    cur.execute(sql, [id])

    # Remove 1 to the id to get continuity
    sql = 'UPDATE sqlite_sequence SET seq = seq - 1 WHERE name="wordlists"'
    cur = conn.cursor()
    cur.execute(sql)
    
    conn.commit()
    return redirect(url_for('main.wordlist'))

@main.route('/tasks')
@login_required
def tasks():
    conn = get_db_connection()
    tasks = conn.execute('SELECT id, task_name, hash, plaintext, status, time_spent, result, hash_type FROM tasks')
    return render_template('tasks.html', tasks=tasks)

@main.route('/tasks/delete/<id>', methods=['POST'])
@login_required
def del_task(id):
    conn = get_db_connection()

    # Remove a row
    sql = 'DELETE FROM tasks WHERE id=?'
    cur = conn.cursor()
    cur.execute(sql, [id])
    
    conn.commit()
    return redirect(url_for('main.tasks'))

@main.route('/users')
@login_required
def users():
    users = User.query.all()
    return render_template('users.html', users=users)

@main.route('/users/delete/<id>', methods=['POST'])
@login_required
def del_user(id):
    conn = get_db_connection()

    # Remove a row
    sql = 'DELETE FROM user WHERE id=?'
    cur = conn.cursor()
    cur.execute(sql, [id])
    
    conn.commit()
    return redirect(url_for('main.users'))

@main.route('/supervision')
@login_required
def supervision():
    return redirect(os.getenv('MONITORING_URL') + "/grafana", code=302)

front/templates/attack.html
{% extends "base.html" %}

{% block content %}

<head>
  <script type='text/javascript'>
    function addFields() {
      // Generate a dynamic number of inputs
      var number = document.getElementById("range").value;
      // Get the element where the inputs will be added to
      var container = document.getElementById("container");

      var options_str = "";
      "{% for wordlist in wordlists %}"
      options_str += '<option value="' + "{{ wordlist.name }}" + '">' + "{{ wordlist.name }}" + '</option>';
      "{% endfor %}"

      // Remove every children it had before
      while (container.hasChildNodes()) {
        container.removeChild(container.lastChild);
      }
      for (i = 1; i <= number; i++) {
        let input = document.createElement("input");
        input.type = "text";
        input.name = "Worker " + i;

        let col = document.createElement('div')
        col.className = 'col-sm-4'
        col.style = 'margin-bottom: 24px;'

        let card = document.createElement('div')
        card.className = 'card'

        let cardBody = document.createElement('div')
        cardBody.className = 'card-body'

        let title = document.createElement('h5')
        title.innerText = input.name;
        title.className = 'card-title';

        let subtitle = document.createElement('h6')
        subtitle.innerText = 's-1vcpu-1gb';
        subtitle.className = 'card-subtitle mb-2 text-muted';

        let formSelect = document.createElement('select')
        formSelect.className = 'form-select'
        formSelect.innerHTML = options_str;
        formSelect.name = "select" + i;

        container.appendChild(col);
        col.appendChild(card);
        card.appendChild(cardBody);
        cardBody.appendChild(title);
        cardBody.appendChild(subtitle);
        cardBody.appendChild(formSelect);

      }
      let buttonMB = document.createElement('div')
      buttonMB.className = "mb-3"

      let button = document.createElement('button')
      button.className = "btn btn-primary"
      button.type = "submit"
      button.innerText = "Create"

      container.appendChild(buttonMB)
      buttonMB.appendChild(button)
    }
  </script>
</head>

<h1 class="title">
  Attack
</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-danger" role="alert">
  {{ messages[0] }}
</div>
{% endif %}
{% endwith %}

<form action="/api/create" method="post">
  <div class="mb-3">
    <label class="form-label">Task name</label>
    <input type="text" name="task-name" class="form-control" required>
  </div>
  <div class="mb-3">
    <label class="form-label">Hash type</label>
    <select name="hash-type" class="form-select" required>
      <option value="" selected>Select a hash type</option>
      {% for type in hash_type %}
      <option value="{{ type.type_name }}">{{ type.type_name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="mb-3">
    <label class="form-label">Hash</label>
    <input type="text" name="hash" class="form-control" required>
  </div>
  <div class="mb-3">
    <label class="form-label">Number of instances : </label>
    <output id="num">1</output>
    <input type="range" id="range" name="number" class="form-range" value="1" min="1" max="10" step="1"
      oninput="num.value = this.value" required>
  </div>
  <a href="#" class="btn btn-secondary mb-3" role="button" id="filldetails" onclick="addFields()">Select</a>
  <!-- JS Container -->
  <div class="row" id="container"></div>
  <!-- JS Container -->
</form>

{% endblock %}

front/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hashton</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            font: 14px sans-serif;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .wrapper {
            width: 720px;
            padding: 20px;
            margin: 0 auto;
            flex: 1;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Hashton</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">   
                        <a class="nav-link" href="{{ url_for('main.dashboard') }}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.attack') }}">Attack</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.wordlist') }}">Wordlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.tasks') }}">Tasks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.users') }}">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.supervision') }}" target="_blank">Supervision</a>
                    </li>
                    {% endif %}
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>

</html>

front/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<h1>Dashboard</h1>

<!--Auto refresh every 3 seconds-->
<meta http-equiv="refresh" content="3">

<style>
    .wrapper {
        width: 900px;
    }
</style>

<div class="row">
    {% for worker in workers %}
    <div class="col-sm-4" style="margin-bottom: 24px;">
        <div class="card">
            <form method="POST" action="/api/destroy/{{ worker.instance_name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ worker.instance_name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ worker.internal_ip }}</h6>
                    <p class="card-text"><i>{{ worker.task_wordlist }}</i><br><b>{{ worker.task_status }}</b></p>
                    {% if worker.instance_status == "Creating" %}
                    <div class="progress" style="margin-bottom: 16px;">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" id="progress-bar"
                            style="width: 100%;">Creating</div>
                    </div>
                    {% else %}
                    <div class="progress" style="margin-bottom: 16px;">
                        <div class="progress-bar progress-bar-striped progress-bar-animated " id="progress-bar"
                            style="width: {{ worker.task_progression }}%;">{{ worker.task_progression }}%</div>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <button type="submit" style="width: 45%;" class="btn btn-outline-danger float-">Destroy</button>
                    </div>                
                </div>
            </form>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

front/templates/login.html
{% extends "base.html" %}

{% block content %}

<head>
  <style>
    .wrapper {
      width: 360px;
    }
  </style>
</head>

<h1>Login</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-danger" role="alert">
  {{ messages[0] }}
</div>
{% endif %}
{% endwith %}

<form method="POST" action="/login">
  <div class="mb-3">
    <label class="form-label">Email address</label>
    <input type="email" name="email" class="form-control">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" name="password" class="form-control">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" name="remember" class="form-check-input">
    <label class="form-check-label">Remember</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

front/templates/signup.html
{% extends "base.html" %}

{% block content %}

<head>
  <style>
    .wrapper {
      width: 360px;
    }
  </style>
</head>

<h1>Sign up</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-danger" role="alert">
  {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
</div>
{% endif %}
{% endwith %}

<form method="POST" action="/signup">
  <div class="mb-3">
    <label class="form-label">Email address</label>
    <input type="email" name="email" class="form-control">
  </div>
  <div class="mb-3">
    <label class="form-label">Full Name</label>
    <input type="text" name="name" class="form-control">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" name="password" class="form-control">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

front/templates/tasks.html
{% extends "base.html" %}

{% block content %}
<h1>Tasks</h1>

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
    <style>
        .wrapper {
            width: 1200px;
        }
    </style>
</head>

<table id="table" class="table table-striped">
    <thead class="table-dark">
        <tr>
            <th>ID</th>
            <th>Task name</th>
            <th>Type</th>
            <th>Hash</th>
            <th>Plaintext</th>
            <th>Status</th>
            <th>Time spent</th>
            <th>Result</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.id }}</td>
            <td>{{ task.task_name }}</td>
            <td>{{ task.hash_type }}</td>
            <td>{{ task.hash }}</td>
            {% if task.plaintext != "---" %}
            <td><b>{{ task.plaintext }}</b></td>
            {% else %}
            <td>{{ task.plaintext }}</td>
            {% endif %}
            <td>{{ task.status }}</td>
            <td>{{ task.time_spent }}</td>
            {% if task.result == "OK" %}
            <td style="color: green;"><b>{{ task.result }}</b></td>
            {% elif task.result == "FAILED" %}
            <td style="color: red;"><b>{{ task.result }}</b></td>
            {% else %}
            <td>{{ task.result }}</td>
            {% endif %}
            <td>
                <form action="tasks/delete/{{ task.id }}" method="post">
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

front/templates/users.html
{% extends "base.html" %}

{% block content %}
<h1>Users management</h1>

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
    <style>
        .wrapper {
            width: 1000px;
        }
    </style>
</head>

<div class="mb-5">
    <table id="table" class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.creation_date }}</td>
                <td>
                    <form action="users/delete/{{ user.id }}" method="post">
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>                    
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

front/templates/wordlist.html
{% extends "base.html" %}

{% block content %}
<h1>Wordlist Generation</h1>

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
    <style>
        .wrapper {
            width: 1000px;
        }
    </style>
</head>

<div class="mb-5">
    <table id="table" class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Link</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for wordlist in wordlists %}
            <tr>
                <td>{{ wordlist.id }}</td>
                <td>{{ wordlist.name }}</td>
                <td>{{ wordlist.url }}</td>
                <td>
                    <form action="wordlist/delete/{{ wordlist.id }}" method="post">
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>                    
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<h2>Add wordlist</h2>

<form action="/wordlist" method="post" class="row g-3">
    <div class="col-md-3">
        <label class="form-label">Name</label>
        <input type="text" class="form-control" name="name">
    </div>
    <div class="col-md-9">
        <label class="form-label">Link</label>
        <input type="url" class="form-control" name="url">
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Insert</button>
    </div>
</form>

{% endblock %}